export type GeneralizedServerVariables = {
	SERVER_VAR_EXPRESS_PORT: number;
	SERVER_VAR_GMAIL_NOTIFICATIONS_SEND_FROM_EMAIL: string;
	SERVER_VAR_GMAIL_NOTIFICATIONS_SEND_FROM_NAME: string;
	SERVER_VAR_GMAIL_NOTIFICATIONS_USER_ID: string;
	SERVER_VAR_ORIGIN_HTTP: string;
	SERVER_VAR_ORIGIN_HTTPS: string;
	SERVER_VAR_SITE_ORIGIN_BY_TARGET: Record<string, string>;
};
